#!/usr/bin/env bash

set -e

CROSS_ROOT=$(realpath .)/cross-root
export PATH=$CROSS_ROOT/bin:$PATH

install_package() {
    for t in $PKG_TOOLS; do
        export PATH=$CROSS_ROOT/tools/$t/bin:$PATH
    done

    PKG_PREFIX=$CROSS_ROOT/tools/$1

    cd tools/$1

    ( pkg_fetch )
    ( pkg_build )
    ( pkg_install )

    touch installed
}

install_packages() {
    for i in "$@"; do
        if [ -f tools/$i/installed ]; then
            echo "Package $i already installed."
            continue
        fi

        . tools/$i/def.pkg

        echo "Installing $PKG_NAME ($PKG_VERSION)..."
        echo "Tools:     $PKG_TOOLS"

        ( install_packages $PKG_TOOLS )

        ( install_package $i )
    done
}

clean_packages() {
    for i in "$@"; do
        . tools/$i/def.pkg

        echo "Cleaning $PKG_NAME ($PKG_VERSION)..."

        ( cd tools/$i && pkg_clean )
    done
}

case $1 in
    install)
        install_packages "${@:2}";;
    clean)
        clean_packages "${@:2}";;
    *)
        printf "\e[33m'$1' is an invalid command!\e[0m\n" 1>&2
        exit 1
        ;;
esac
